### ISSUE TITLE
gdcmaf: identify child process memory use to identify bigger size limit

### ISSUE THREAD

**Issue by xzhou82** [stjude/proteinpaint#1046]
look into memuse crate suggested by Robin
once we settle on a bigger cutoff number, encode it into serverconfig.json of gdc environment (to ask Edgar)

**Comment by josephpowi** [comment]
Memuse crate is used to estimate the amount of heap-allocated memory used by a type (for example a vector). We used to download all maf data in memory so that it is possible to identify the usage of memory using Memuse. 

Now we don't download and assign all data to a variable. The data is downloaded and transferred to stdout through the stream. It is not able to use Memuse to estimate the memory usage. I already used some tools to monitor the memory during the running of rust code, the maximum memory used is around 18M.

**Comment by xzhou82** [comment]
thanks
