### ISSUE TITLE
niceNumLabels error when using regression interface

### ISSUE THREAD

**Issue by gavrielm** [stjude/proteinpaint#1693]
Open developer console -> Begin a [regression analysis](http://localhost:3000/?noheader=1&mass={%22genome%22:%22hg38%22,%22dslabel%22:%22SJLife%22,%22nav%22:{%22activeTab%22:1},%22plots%22:[{%22chartType%22:%22regression%22,%22regressionType%22:%22linear%22,%22outcome%22:{%22id%22:%22LV_Ejection_Fraction_3D%22}}]}) -> for independent variable, add `Variants in a locus` -> client-side error emitted from `niceNumLabels.ts`

**Comment by xzhou82** [comment]
thanks for finding it. it's caused by filter UI showing vcf INFO fields. also replicable from [genome browser](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22SJLife%22,%22genome%22:%22hg38%22,%22nav%22:{%22activeTab%22:1},%22plots%22:[{%22chartType%22:%22genomeBrowser%22,%22geneSearchResult%22:{%22chr%22:%22chr10%22,%22start%22:61901683,%22stop%22:62096944}}]}) which shows same filter. looking now
