### ISSUE TITLE
top mutated genes request returns genes with 0 rendered hits (only has CNV)

### ISSUE THREAD

**Issue by siosonel** [stjude/proteinpaint#1985]
(EDIT: has to do with CNV not being displayed initially in the matrix plot) MUC16 and sometimes a few other genes seem to always be returned as a top gene, even though they have 0 hits. 
- Direct server request: http://localhost:3000/gdc/topMutatedGenes?maxGenes=10&geneFilter=CGC&embedder=localhost
- can also view rendered plot with http://localhost:3000/example.gdc.matrix.html?maxGenes=10

![Screenshot 2024-08-06 at 1 54 15 PM](https://github.com/user-attachments/assets/5ba3ab9a-6833-4341-a572-3311b66bb4ce)

**Comment by xzhou82** [comment]
looks to me the "GenesTable" graphql query returns unfiltered number of ssm-mutated cases for every gene. e.g. at http://localhost:3000/example.gdc.matrix.html?cohort=Gliomas and you launch genesetedit ui and load top genes, the number of ssm cases are thousands instead of only 900

**Comment by siosonel** [comment]
> GenesTable

but even when I have `All GDC` and no cohort filter, MUC16 still shows up as a top mutated gene.

**Comment by xzhou82** [comment]
MUC16 seems always show for a few cohorts i've tried, despite it's not mutated in any

**Comment by xzhou82** [comment]
big issue: portal OncoMatrix displays MUC16 mutated cases for most cohorts, while on local it doesn't, while local also uses prod API

cause: it is due to gencode.v36 vs v43. MUC16 and those genes with n=0 are using a default isoform not found in v36. thus our code when running on portal and hooked to v36, will show diff results!
