### ISSUE TITLE
manual tape test can no longer appropriately report err

### ISSUE THREAD

**Issue by xzhou82** [stjude/proteinpaint#2266]
revert this [change](https://github.com/stjude/proteinpaint/pull/2265/commits/58322a9bb25610b0146535bd482e020672112064) and [this test](http://localhost:3000/testrun.html?dir=gdc&name=bam) breaks saying __dirname is missing, rather than actual error

**Comment by siosonel** [comment]
Below is what I see after reverting, maybe the `__dirname is missing`  error was due to some other error or requires a particular sequence of steps to recreate with the manual test.

![Screenshot 2024-10-16 at 1 51 29 PM](https://github.com/user-attachments/assets/e7fe7911-dcf0-4b8e-8278-47fbafd944a9)
