### ISSUE TITLE
colorscale: setMinMax should return {type:'auto/fixed',min,max} and allow to switch between auto/fixed as dom/numericAxis.js 

### ISSUE THREAD

**Issue by xzhou82** [stjude/proteinpaint#2301]
details to be fully specified

**Comment by creilly8** [comment]
@xzhou82, Instead of using a toggle for auto and fixed, why not use a reset button? In this UI the user isn't setting multiple ranges, using special characters, creating bins, etc. Regardless if it's auto or fixed, the user will be shown the min and max, unlike the numericAxis UI. So instead of toggle or radio button to switch between the two modes, why not provide a reset button to go back to the min and max determined on render? It would simplify the UI and still accomplish the same functionality. What do you think?
