### ISSUE TITLE
new procedure to gracefully handle mds3 ds recoverable error during init

### ISSUE THREAD

**Issue by xzhou82** [stjude/proteinpaint#2477]
a ds may define `init{}` allowing to retry initiation on recoverable error. this may only be set on gdc to handle network requests
a ds without `init{}` may always fail and will not retry initiation (e.g. vcf file missing for a native ds)

a ds may set either of two new properties to indicate errors during init:
- ds.__recoverableInitError: human readable err string that is recoverable. only set it when ds is indeed recovering the error. when recovered, this property will be deleted. the ds will be ready to do business
- ds.__nonrecoverableInitError: human readable err string that is unrecoverable. the ds makes no attempt at recovering such. the ds will not be ready for business
- for client to know about this, send these two errors with termdbConfig{}. client (mass, mds3 tk etc) needs to detect such and indicate to user the ds is out of business (and may be back soon)

changes to mds3.init.js:
1. this function should be coded up in a way it will never throw, thus `initGenomeDs.js` will never need to try-catch it
2. will continue

**Comment by siosonel** [comment]
I think the logic for  `init()` and retry option in `mds3.init.js` could be made simpler:
- wrap the code inside it in a try-catch block, including the optional `ds.preInit.getStatus()`, so no need for special `mayRetryDsPreInit()` handling since all code inside the try block may be retried as a whole 
- an error in any of the optional preInit.getStatus and required `validate_*()` functions should bubble up into this top level init catch block
- if `retryMax < 1 || fatalError`, put the error message in an `init_errors` array, do not throw
- else `setInterval(()=>{ try {init(ds, genome, serverconfig)} catch(e) {}, retryDelay` - which is basically what my current PR does inside `runRemainingWithoutAwait()` but for `cacheMappingOnNewRelease()` instead of the overall `init()`
- at the end of `initGenomeDs()`, alert team if `init_errors` is not empty, this would contain fatal errors (that was not thrown so it doesn't crash the server)
- for recoverable errors, alert the team of maybe the initial retry and for sure the last retry
